In [22]:
import numpy as np
import pandas as pd
import matplotlib

In [14]:
### create a list
lst = [1, 2, 3, 4, 5 ]

### create array from list
### create array from list
# np_arr = np.array(lst)
# np_arr
np_arr = np.array(lst, dtype=np.int8)
np_arr

array([1, 2, 3, 4, 5], dtype=int8)

In [15]:
print(matplotlib.__version__)

3.9.0


In [16]:
### multi-dimensional list ==> array
m_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

np_m_arr = np.array(m_list)   ### pass the list into the array function
np_m_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
### https://numpy.org/doc/stable/reference/generated/numpy.arange.html
np.arange(1, 10)   ### note the last element is 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
### stepping
np.arange(1, 10, 2)

## stepping issues: side effect with arange(); use linspace instead
np.arange(0, 5, 0.5, dtype=int)
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [25]:
### linspace https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace
np.linspace(0, 5, 7)
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
### zero array
np.zeros(4)

## multi-dimensional array filled with zeros
np.zeros((2, 4))

## filled with one's
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
### size of array
np_m_arr.size

9

In [29]:
np_arr_2 = np.array([1, 2, 3, 4, 5])

In [30]:
np_arr

array([1, 2, 3, 4, 5], dtype=int8)

In [32]:
np_arr_2
np_arr_2.dtype

dtype('int64')

In [33]:
### data types
# Boolean: np.bool_
# Char: np.byte
# Short: np.short
# Integer: np.short
# Long: np.int_
# Float: np.single & np.float32
# Double: np.double & np.float64
# np.int8: -128 to 127
# np.int16: -32768 to 32767
# np.int32: -2147483648 to 2147483647
# np.int64: 


In [38]:
### random arrays
np.random.randint(10, 50, 5 )
np.random.randint(10, 50, size = (2, 3) )

array([[35, 41, 29],
       [18, 28, 10]])

In [49]:
##### how to learn more about a function? #####
# np.random.randint?
#####

In [74]:
np.random.randint(1, 5, 100)

array([3, 1, 2, 4, 1, 1, 3, 2, 2, 1, 2, 4, 1, 3, 1, 3, 3, 1, 2, 1, 2, 1,
       4, 2, 3, 2, 4, 1, 2, 2, 3, 1, 1, 2, 1, 4, 4, 3, 1, 2, 2, 1, 3, 1,
       2, 1, 4, 3, 4, 3, 1, 3, 1, 4, 3, 4, 1, 1, 2, 4, 1, 4, 4, 1, 2, 1,
       4, 3, 2, 4, 1, 4, 3, 2, 1, 4, 1, 4, 2, 1, 4, 2, 2, 2, 2, 4, 1, 4,
       2, 1, 2, 4, 4, 4, 4, 3, 2, 1, 1, 3])