In [29]:
import pandas as pd
import numpy as np
# import random ##### just use np

In [30]:
np.random.randint(1, 500, 5)
np.random.randint(1, 500, size = (5, 10))

array([[435, 257, 154, 449, 118, 162,  83, 314,  95,  19],
       [ 42, 466, 298, 287, 261, 284, 202, 334, 267, 476],
       [114, 186, 148, 139,  35, 123, 446, 200, 482, 413],
       [299, 246, 270, 443, 108, 151, 102, 384, 362, 233],
       [ 78,  73, 113, 484, 179, 391, 380, 363,  20,  53]])

In [31]:
m_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

np_m_arr = np.array(m_list)
np_m_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
### modify array elements
np_m_arr[0, 0] = 100

In [33]:
print('array np_m_arr:\n', np_m_arr)

array np_m_arr:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [34]:
np_m_arr.itemset((0, 1), 999)
np_m_arr

array([[100, 999,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [35]:
### shape
np_m_arr.shape

(3, 3)

In [36]:
### get 
np_m_arr[0, 0]

100

In [37]:
### get
np_m_arr.item(0, 0)

100

In [38]:
### show using take()
np.take(np_m_arr, [0, 1, 2, 3])

array([100, 999,   3,   4])

In [39]:
### 
### put()
np.put(np_m_arr, [0, 3, 6], [100, 100, 100])
np_m_arr

array([[100, 999,   3],
       [100,   5,   6],
       [100,   8,   9]])