## Conditional Statement

In [14]:
### import modules
import numpy as np
import pandas as pd

In [15]:
np.random.randint( 10, 50, size=(2,3) )

array([[47, 42, 26],
       [32, 39, 15]])

In [16]:
arr = np.random.randint( 10, 50, size=(2,3) )
print(arr)

[[28 42 29]
 [14 34 27]]


In [17]:
### set up dataframe
df = pd.DataFrame(arr, ['A', 'B'], ['C', 'D', 'E'])
df
# print(df)

C   D   E
A  28  42  29
B  14  34  27

In [18]:
### conditional
print("Show greater than 30\n", df > 30, '\n')
print("Show greater than 30\n", df.gt(30))     ### le, ge, le, eq, ne

Show greater than 30
        C     D      E
A  False  True  False
B  False  True  False 

Show greater than 30
        C     D      E
A  False  True  False
B  False  True  False


In [19]:
bool = df >= 30
df[bool]


C   D   E
A NaN  42 NaN
B NaN  34 NaN

In [20]:
df['E']
print(df['E'] > 30)

A    False
B    False
Name: E, dtype: bool


In [21]:
print(df, '\n')
df[df['E'] > 30 ]

    C   D   E
A  28  42  29
B  14  34  27 



Empty DataFrame
Columns: [C, D, E]
Index: []

In [22]:
df_2 = df[df['E'] > 30 ]
df_2['C']

Series([], Name: C, dtype: int64)

In [23]:
dates = pd.date_range("20230101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2023-01-01  1.264312 -0.204378  1.071795  0.207472
2023-01-02 -1.107431 -0.144763  0.371513  0.702322
2023-01-03  0.228157 -0.045640  0.952287  0.358318
2023-01-04  0.252755 -0.285835  1.699257 -0.168782
2023-01-05 -0.428454  0.610120  0.159778 -1.106159
2023-01-06 -0.043981 -1.549413  0.037325  0.075119

In [24]:
# quiz scores with index and columns
df = pd.DataFrame(np.random.randint(0, 100, size=(4, 6)), 
                  index=["Jay", "Riley", "Sayok", "Jake"], 
                  columns=[1, 2,3,4,5,6])
df
# df = pd.DataFrame(np.random.randn(0, 10, size=(4, 6)))
# df

1   2   3   4   5   6
Jay    77  99  66  64   3  38
Riley  59  56  36  91  24  35
Sayok  84  46  56  85  36  35
Jake   58  15  25  14   4  11

In [25]:
df[df[6] > 30 ] 

1   2   3   4   5   6
Jay    77  99  66  64   3  38
Riley  59  56  36  91  24  35
Sayok  84  46  56  85  36  35

In [26]:
df[6]

Jay      38
Riley    35
Sayok    35
Jake     11
Name: 6, dtype: int64

In [27]:
df[df[6] > 30][6] 

Jay      38
Riley    35
Sayok    35
Name: 6, dtype: int64

In [28]:
df[df[6] > 30][[5, 6] ]

5   6
Jay     3  38
Riley  24  35
Sayok  36  35

In [29]:
### numpy array of quiz scores
arr = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [7,8,9,10]
])
# arr
df = pd.DataFrame(arr, index=['Aaron', 'Bill', 'Cloe'], columns=[1,2,3,4])
df

1  2  3   4
Aaron  1  2  3   4
Bill   4  5  6   7
Cloe   7  8  9  10

In [30]:
### multiple conditions
df[ (df[3] > 5 ) & (df[4] > 5) ]

1  2  3   4
Bill  4  5  6   7
Cloe  7  8  9  10